### ISSUE TITLE
Support native Docker for OS X and Windows

### ISSUE THREAD

**Issue by proofoftom** [blinkreaction/drude#113] opened 2016-05-05 23:31 UTC
Now that there's a native Docker client [(in beta)](https://blog.docker.com/2016/03/docker-for-mac-windows-beta/) for Mac and Windows, Drude shouldn't need a boot2docker VM if the machine is running native Docker.

**Comment by lmakarov** [comment] 2016-05-06 02:03
Unfortunately the "native" implementation is slow like hell.
xhyve on Mac is very far away from being good. Shared volumes are done via fuse and are terribly slow.

Here are some numbers. I'm suing a simple `time drush si -y` test (D7):

```
boot2docker-vagrant (virtualbox, nfs): 7.554s
docker beta (xhyve, fuse.osxfs): 57.796s
boot2docker (virtualbox, vboxsf): 23.612s
```

As you can see docker beta performance is much worse than the original stock boot2docker.

Performance concerns with shared files was the main driver for https://github.com/blinkreaction/boot2docker-vagrant to be born and used by Drude.

One day will be running docker "natively" on Mac and Windows, but that day is not yet close...

**Comment by lmakarov** [comment] 2016-05-06 02:10
BTW Docker Beta on Windows should be in a better state. They are doing SMB out of the box for shared folders.

I need to run the tests, but expecting the results to be pretty close.

The one VERY annoying thing on Window, though, is that Docker switched to Hyper-V, which locks VT-x to itself. Nothing else (VirtualBox/etc.) will function, unless you completely remove Hyper-V.

**Comment by james-nesbitt** [comment] 2016-05-06 06:50
Just a heads up, we are discovering that most of the speed and latency issues on the native docker clients are poor network routing and resolving, as opposed to xhyve/hypervisor and fs woes.

In particular, this one is killing us: https://forums.docker.com/t/ip-routing-to-container/8424

[edit: ps. interesting work going on at drude]

**Comment by james-nesbitt** [comment] 2016-05-06 06:53
@lmakarov do you know if the windows smb is mapping users like the osx implementation?

**Comment by lmakarov** [comment] 2016-05-18 16:12
@james-nesbitt what do you mean by "mapping users"?

BTW I’ve put together a comparison of Docker Beta (native fs vs fuse) vs boot2docker-vagrant (native fs vs vboxsf vs nsf) and PHP5.6 vs PHP7.

Using `time drush si -y` with Drupal 7 as a test case.
The first run in every case is a cold start. Averaging across 3 runs in each case.

![Docker Beta vs boot2docker-vagrant + PHP5.6 vs PHP7](http://take.ms/gRfYm)

So Docker Beta IS in fact the fastest option if using native file system.
At the same time Docker Beta is the slowest option when mounting the host file system.

Also notice how close `native fs` and `nfs` are with `boot2docker-vagrant`

**Comment by proofoftom** [comment] 2016-05-22 08:46
That's great to know and definitely provides insight into the mounting performance. I'm closing this issue for now since boot2docker obviously makes more sense at the moment.

**Comment by lmakarov** [comment] 2016-06-01 13:39
Let's keep this one open to track Docker Beta evolvement.

Here's another set of test results with `1.11.1-beta13.1` (previous one was using `1.11.1-beta12`)

![Docker Beta, PHP5.6 vs PHP7](http://take.ms/cfToz)

Things are getting better with `osxfs`. In fact, there is a 2x improvement! :)

**Comment by jmarkel** [comment] 2016-07-21 17:55
This is not really an acceptable excuse. When you download Docker for Mac you get the native Mac beta release by default, with no indication that it even is a beta (other than in the download url). The default configuration should work with native Docker in addition to boot2docker-vagrant, perhaps with a warning on installation that performance will be better with boot2docker-vagrant.

To be honest, if one is required to install Vagrant anyway, there's little compelling reason to use Docker at all.

**Comment by achekulaev** [comment] 2016-09-21 03:43
[Docksal](https://github.com/docksal/docksal)

**Closed as completed by achekulaev** 2016-09-21 03:43 UTC

**Comment by jmarkel** [comment] 2016-09-21 12:01
Docksal requires Vagrant. That is NOT native Docker. This ticket should NOT be closed, since Docksal does not address it.

**Comment by achekulaev** [comment] 2016-09-21 18:11
@jmarkel no it does not require Vagrant

**Comment by jmarkel** [comment] 2016-09-21 19:29
Pardon me - VirtualBox, not Vagrant. But Native Docker does not require VBox or DockerMachine, it runs natively without additional virtualization tools.

"Docksal software requirements for Mac and Windows:

VirtualBox 5.0+
You need to install it manually before running Docksal."

**Comment by achekulaev** [comment] 2016-09-21 19:48
Docksal is in Beta and it's documentation is in the process of update however it will support native Docker when released. It already partially supports it. Drude will be discontinued. Any related work will be only done in Docksal. Hence the issue is closed.
