### ISSUE TITLE
Vagrant and VirtualBox version incompatibility problems

### ISSUE THREAD

**Issue by travismagic** [blinkreaction/drude#155] opened 2016-07-14 17:58 UTC
Hello!

I just tried running `dsh install prerequisites` and `dsh install boot2docker`. Vagrant fails on boot2docker.

It appears VirtualBox had a v5.1 release on 7/12. Latest Vagrant (v1.8.4) says it is only compatible with VirtualBox v5.0, so I had to manually downgrade my VirtualBox version.

I know this is an upstream problem, but should we update the install scripts to pull those specific versions?

**Comment by lmakarov** [comment] 2016-07-14 18:16
Hi @travismagic, are you on Mac or Windows?

Brew on Mac did not use to support the ability to point explicitly the current number. In other words, we would have to stick to the previous available version all the time.
I believe Choco on Windows does support this though. So there is an opportunity to improve.

**Comment by travismagic** [comment] 2016-07-14 19:36
Hi @lmakarov, yes I'm on a Mac.

**Comment by kyleskrinak** [comment] 2016-07-27 20:29
FYI: note you should downgrade **both** VB to 5.0.20 AND Vagrant to 1.7.4

**Comment by lmakarov** [comment] 2016-08-03 23:52
Vagrant `1.8.5` should be compatible with the latest VirtualBox `5.1.2` release, however `VirtualBox Guest Additions` version we currently have is `5.0.20` and the latest boot2docker release is at `5.0.24`. Both will most likely have issues with VirtualBox `5.1.2`.

So for now avoid VirtualBox `5.1.2` and stick with:
- Vagrant 1.7.4 - 1.8.4
- VirtualBox 5.0.0 - 5.0.26

We can get versions locked for Windows users in `dsh install prerequisites`, however not for Mac users, as cask does not (and looks like won't) support this...

**Comment by GGolovenko** [comment] 2016-08-04 12:08
Confirmed on mac: downgraded from latest versions to VirtualBox - 5.0.26 and Vagrant 1.8.4
after that it works.

**Comment by lmakarov** [comment] 2016-08-04 17:46
Going to close this in favor of the issue in the upstream project:
https://github.com/blinkreaction/boot2docker-vagrant/issues/83

Let's move further discussions there.

**Closed as completed by lmakarov** 2016-08-04 17:46 UTC
Labels: bug
