### ISSUE TITLE
Unable to mount shared folders

### ISSUE THREAD

**Issue by kyleskrinak** [blinkreaction/drude#156] opened 2016-07-25 20:24 UTC
I ran:

```
dsh self-update
dsh update prerequisites
dsh update boot2docker
```

which, most notably, updated my VBox to 5.1.2, which I've now learned is an issue with Vagrant, as per this ticket #155 

So I've downgraded my VBox to 5.0.20 (which it was at prior to the upgrade) however, I am seeing this error:

> Vagrant was unable to mount VirtualBox shared folders. This is usually
> because the filesystem "vboxsf" is not available. This filesystem is
> made available via the VirtualBox Guest Additions and kernel module.
> Please verify that these guest additions are properly installed in the
> guest. This is not a bug in Vagrant and is usually caused by a faulty
> Vagrant box. For context, the command attemped was:
> 
> set -e
> mount -t vboxsf -o uid=`id -u docker`,gid=`getent group docker | cut -d: -f3` .ssh /.ssh
> mount -t vboxsf -o uid=`id -u docker`,gid=`id -g docker` .ssh /.ssh
> 
> The error output from the command was:
> 
> gid= requires an argument (i.e. gid==<arg>)
> mount: mounting .ssh on /.ssh failed: Protocol error

shelling into the b2d box, I run

```
grep -i vbox
```

and see:

> vboxsf                 40960  0
> vboxguest             180224  2 vboxsf

Only a partial list of [what should be running](http://askubuntu.com/questions/169024/how-can-i-tell-if-the-virtualbox-guest-additions-were-installed-on-an-ubuntu-vm).

I'm unclear of what I can do next to get my drude environment operational again?

**Comment by achekulaev** [comment] 2016-07-26 19:36
Hi @kyleskrinak 

You are not the first reporting this issue. Looks like vagrant did something wrong in their last version which brought a retro-bug. 

Looks like downgrading to VirtualBox 5.0.20 and vagrant 1.7.4 solves the issue.

**Comment by achekulaev** [comment] 2016-07-26 19:41
FYI there is also another fix which does the same but with destroying existing VM altogether. 
I would try it as a last resort http://www.venumurthy.com/2014/02/vagrant-error-failed-to-mount-folders.html

**Comment by kyleskrinak** [comment] 2016-07-26 23:13
@achekulaev Thanks for the suggestions. I did try the vagrant vbguest plugin before I posted. However, I get this message:

> The guest's platform ("tinycore") is currently not supported, will try generic Linux method...

which leads to

> An error occurred during installation of VirtualBox Guest Additions 5.1.2. Some functionality may not work as intended.

I also previously tried `vagrant ssh` into the b2d machine to run this command:

`sudo ln -s /opt/VBoxGuestAdditions-4.3.10/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions`

which I presume should be

`sudo ln -s /opt/VBoxGuestAdditions-5.1.2/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions`

Or whichever version of VBox I'm running. However, the b2d machine only lists

```
bootlocal.sh
bootscript.sh
bootsync.sh
shutdown.sh
tcemirror
```

There's no such dir in /opt.

I'm using Drupal VM until I resolve this, but _really_ miss drude.

**Comment by achekulaev** [comment] 2016-07-27 19:37
Have you tried downgrading to VirtualBox 5.0.20 and vagrant 1.7.4?

**Comment by kyleskrinak** [comment] 2016-07-27 20:28
I had only downgraded VB previously. Downgrading both did the trick. Thanks! Drupal VM is nice, but way overkill, storage-wise.

**Comment by achekulaev** [comment] 2016-07-27 22:44
Great!

I will keep this issue open and update it once it's safe to update to the latest versions. 
Going forward we'll get rid of Vagrant.

**Comment by lmakarov** [comment] 2016-08-04 17:47
This is a duplicate of https://github.com/blinkreaction/drude/issues/155

Closing in favor of the issue in the upstream project:
https://github.com/blinkreaction/boot2docker-vagrant/issues/83

Let's move further discussions there.

**Closed as completed by lmakarov** 2016-08-04 17:47 UTC
Labels: bug

**Comment by edilsoncichon** [comment] 2016-09-20 23:28
This post me helped [Link](https://hacklog.mu/vboxsf-file-system-not-available/) solve this problem.
